# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='stock_code',
            field=models.IntegerField(default=0),
        ),
    ]
