# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_scraper', '0002_comment_stock_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='url',
            field=models.URLField(default='http://'),
        ),
    ]
