# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment_scraper', '0003_comment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='news_website',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='comment_scraper.NewsWebsite'),
            preserve_default=False,
        ),
    ]
