# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_scraper', '0004_comment_news_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
