# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_scraper', '0005_auto_20161230_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
