# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_scraper', '0006_auto_20161230_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='stock_name',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
