# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_scraper', '0007_comment_stock_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='stock_code',
            field=models.IntegerField(default=None),
        ),
    ]
