# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_scraper', '0008_auto_20161231_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.IntegerField(default=None)),
                ('stock_name', models.CharField(max_length=20)),
                ('pos_degree', models.IntegerField(default=None)),
                ('key', models.CharField(max_length=100)),
            ],
        ),
    ]
