# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_scraper', '0009_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='pos_degree',
            field=models.FloatField(default=None),
        ),
    ]
